[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[profile.default.fuzz]
runs = 100

[doc]
out = "docs"
